import { Be_Vietnam_Pro } from "next/font/google";
import "../globals.css";

import Header from "@/components/shared/Header/Header";
import Footer from "@/components/shared/Footer/Footer";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
  variable: "--font-be-vietnam",
})

export const metadata = {
  title: "Home | SkillSphere – Learn Without Limits",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${beVietnamPro.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col justify-between bg-[#f7f7f8]">
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
};
